### ISSUE TITLE
mParticle SDK is conflicting with AppBoy SDK

### ISSUE THREAD

**Issue by etayluz** [mParticle/mParticlePod_Extended#1]
Hi!

Is there a way to install mParticlePod_Extended pod with AppBoy component left out entirely?
It is conflicting with the Appboy-iOS-SDK pod. And the  Appboy-iOS-SDK version is different than the one included with mParticlePod_Extended - and it's the one I need to use. Thanks!

**Comment by dcirne** [comment]
Hi Etay,

We have deprecated this version of the SDK and strongly recommend updating to the latest SDK version [mParticle iOS SDK](https://github.com/mParticle/mParticle-iOS-SDK), where you can do exactly what you're describing.

Our customer success team will contact you shortly.

Best,

Dalmo

**Comment by etayluz** [comment]
Thanks for prompt reply!
I am actually already using mParticle iOS SDK, but receiving this error in console:
"Unable to forward messages from batch. Reason: Data is neither sent from mParticle extended SDK nor via mParticle S2S API"

**Comment by dcirne** [comment]
Etay,

Thank for working with our customer success team to configure Appboy in your app. I will close this ticket now.
